name: syncra
description: Gestión de presupuesto, conversor de divisas y seguimiento de envíos.
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # Para el icono de la app

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  
