// Archivo: lib/core/localization/app_localizations.dart
class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'app_name': 'Global Wallet',
      'budget_tab': 'Presupuesto',
      'converter_tab': 'Conversor',
      'shipping_tab': 'Envíos',
      'local_curr': 'Moneda Local:',
      'base_salary': 'Sueldo Base Mensual',
      'vaults': 'MIS BÓVEDAS (METAS)',
      'add_expense': 'AÑADIR GASTO',
      'name': 'Nombre',
      'amount': 'Monto',
      'cat_shopping': 'Compras',
      'cat_services': 'Servicios',
      'cat_subs': 'Suscrip.',
      'cat_food': 'Comida',
      'cat_others': 'Otros',
      'create_vault': 'Crear Bóveda',
      'withdraw': 'Retirar Fondos',
      'add_funds': 'Añadir Fondos',
      'target': 'Objetivo',
      'saved': 'Ahorrado',
      'available': 'Disponible',
      'net_balance': 'BALANCE LIBRE',
      'quick_conv': 'Conversión Rápida',
      'amount_to_convert': 'Monto a convertir',
      'apply_fee': 'Aplicar Tarifa Proxy/Banco',
      'bank_fee': 'Comisión (%)',
      'scan_price': 'Escanear Precio',
      'reading_text': 'Leyendo...',
      'copied': 'Copiado al portapapeles',
      'process_cart': 'Procesar Carrito',
      'outdated_rates': 'Tasas desactualizadas. Conéctese a internet.',
      'last_update': 'Actualizado:',
      'total_converted': 'Total Escaneado',
      'to_budget': 'Al Presupuesto',
      'to_shipping': 'A Aduanas',
      'scan_receipt': 'Escanear Recibo',
      'origin': 'Origen del artículo',
      'destination': 'Destino (Aduana)',
      'item_price': 'Precio Artículo',
      'weight': 'Peso',
      'proxy_fee': 'Costo Casillero (Proxy)',
      'cost_breakdown': 'Desglose de Costos',
      'item_value_usd': 'Valor del Artículo (USD)',
      'freight_usd': 'Flete Internacional (USD)',
      'proxy_usd': 'Servicio Proxy (USD)',
      'customs_tax': 'Impuestos de Aduana',
      'total_to_pay': 'Total Estimado',
      'save': 'Guardar',
      'saved_quotes': 'Cotizaciones Guardadas',
      'no_quotes_yet': 'No hay cotizaciones guardadas.',
      'no_price_found': 'No se encontraron precios claros en la imagen.',
    },
    'en': {
      'app_name': 'Global Wallet',
      'budget_tab': 'Budget',
      'converter_tab': 'Converter',
      'shipping_tab': 'Shipping',
      'local_curr': 'Local Currency:',
      'base_salary': 'Monthly Base Salary',
      'vaults': 'MY VAULTS (GOALS)',
      'add_expense': 'ADD EXPENSE',
      'name': 'Name',
      'amount': 'Amount',
      'cat_shopping': 'Shopping',
      'cat_services': 'Services',
      'cat_subs': 'Subs',
      'cat_food': 'Food',
      'cat_others': 'Others',
      'create_vault': 'Create Vault',
      'withdraw': 'Withdraw',
      'add_funds': 'Add Funds',
      'target': 'Target',
      'saved': 'Saved',
      'available': 'Available',
      'net_balance': 'NET BALANCE',
      'quick_conv': 'Quick Conversion',
      'amount_to_convert': 'Amount to convert',
      'apply_fee': 'Apply Bank/Proxy Fee',
      'bank_fee': 'Fee (%)',
      'scan_price': 'Scan Price',
      'reading_text': 'Reading...',
      'copied': 'Copied to clipboard',
      'process_cart': 'Process Cart',
      'outdated_rates': 'Outdated rates. Please connect to internet.',
      'last_update': 'Last update:',
      'total_converted': 'Scanned Total',
      'to_budget': 'To Budget',
      'to_shipping': 'To Customs',
      'scan_receipt': 'Scan Receipt',
      'origin': 'Item Origin',
      'destination': 'Destination (Customs)',
      'item_price': 'Item Price',
      'weight': 'Weight',
      'proxy_fee': 'Proxy/Locker Fee',
      'cost_breakdown': 'Cost Breakdown',
      'item_value_usd': 'Item Value (USD)',
      'freight_usd': 'Intl Freight (USD)',
      'proxy_usd': 'Proxy Service (USD)',
      'customs_tax': 'Customs Tax',
      'total_to_pay': 'Estimated Total',
      'save': 'Save',
      'saved_quotes': 'Saved Quotes',
      'no_quotes_yet': 'No quotes saved yet.',
      'no_price_found': 'No clear prices found in the image.',
    },
    'pt': {
      'app_name': 'Global Wallet',
      'budget_tab': 'Orçamento',
      'converter_tab': 'Conversor',
      'shipping_tab': 'Envios',
      'local_curr': 'Moeda Local:',
      'base_salary': 'Salário Base Mensal',
      'vaults': 'MEUS COFRES (METAS)',
      'add_expense': 'ADICIONAR DESPESA',
      'name': 'Nome',
      'amount': 'Valor',
      'cat_shopping': 'Compras',
      'cat_services': 'Serviços',
      'cat_subs': 'Assinat.',
      'cat_food': 'Comida',
      'cat_others': 'Outros',
      'create_vault': 'Criar Cofre',
      'withdraw': 'Retirar',
      'add_funds': 'Adicionar',
      'target': 'Objetivo',
      'saved': 'Guardado',
      'available': 'Disponível',
      'net_balance': 'SALDO LÍQUIDO',
      'quick_conv': 'Conversão Rápida',
      'amount_to_convert': 'Valor a converter',
      'apply_fee': 'Aplicar Taxa Bancária',
      'bank_fee': 'Taxa (%)',
      'scan_price': 'Escanear Preço',
      'reading_text': 'Lendo...',
      'copied': 'Copiado para a área de transferência',
      'process_cart': 'Processar Carrinho',
      'outdated_rates': 'Taxas desatualizadas. Conecte-se à internet.',
      'last_update': 'Atualizado:',
      'total_converted': 'Total Escaneado',
      'to_budget': 'Ao Orçamento',
      'to_shipping': 'À Alfândega',
      'scan_receipt': 'Escanear Recibo',
      'origin': 'Origem do Item',
      'destination': 'Destino (Alfândega)',
      'item_price': 'Preço do Item',
      'weight': 'Peso',
      'proxy_fee': 'Custo do Proxy',
      'cost_breakdown': 'Detalhamento de Custos',
      'item_value_usd': 'Valor do Item (USD)',
      'freight_usd': 'Frete Internacional (USD)',
      'proxy_usd': 'Serviço Proxy (USD)',
      'customs_tax': 'Imposto Aduaneiro',
      'total_to_pay': 'Total Estimado',
      'save': 'Salvar',
      'saved_quotes': 'Cotações Salvas',
      'no_quotes_yet': 'Nenhuma cotação salva.',
      'no_price_found': 'Nenhum preço claro encontrado na imagem.',
    }
  };

  static String translate(String langCode, String key) {
    if (!_localizedValues.containsKey(langCode)) {
      langCode = 'en'; // Fallback a inglés
    }
    return _localizedValues[langCode]?[key] ?? key;
  }
}
