name: Syncra App Build (CI/CD)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-android:
    name: Compilar APK Android
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Descargar repositorio
        uses: actions/checkout@v4

      - name: ☕ Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🐦 Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 🪄 MAGIA PARA CELULARES: Crea la carpeta 'android' temporalmente en la nube
      - name: 🪄 Generar archivos nativos (Android)
        run: flutter create --platforms=android .

      # 🔧 MAGIA PARA ML KIT: Cambia la versión de Android a 24 automáticamente sin abrir el archivo
      - name: 🔧 Ajustar minSdkVersion para OCR
        run: sed -i 's/flutter.minSdkVersion/24/g' android/app/build.gradle

      - name: 📦 Instalar dependencias
        run: flutter pub get

      - name: ⚙️ Ejecutar Build Runner (Hive)
        run: dart run build_runner build --delete-conflicting-outputs

      # Ignora fallos si no tienes el archivo del logo subido aún
      - name: 🎨 Generar íconos nativos
        run: dart run flutter_launcher_icons || echo "Aviso: Logo no encontrado, usando ícono por defecto."

      # Analiza el código pero no cancela la compilación si hay advertencias (warnings)
      - name: 🔍 Analizar código
        run: flutter analyze --no-fatal-infos --no-fatal-warnings || true

      - name: 🏗️ Compilar APK
        run: flutter build apk --release

      - name: 📤 Subir artefacto (APK)
        uses: actions/upload-artifact@v4
        with:
          name: syncra_app_android_apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          
